### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jayaraj-dckap** [klevultd/frontend-sdk#100] opened 2022-08-02 06:18 UTC
I tried to integrate the same as in our app but while importing the function it throws an error.

Code:
![image](https://user-images.githubusercontent.com/92306881/182305170-eb9c0dd8-f267-4367-94f4-981ce4e33c66.png)

Error: 
![image](https://user-images.githubusercontent.com/92306881/182305217-5b4d1fd3-5a83-4868-86e0-17309ef7ba01.png)

I Am trying to integrate recommended products into our app like the below screenshot.

![image](https://user-images.githubusercontent.com/92306881/182305249-3439ea66-861a-48e9-bae0-1ea533a5968c.png)

**Comment by rallu** [comment] 2022-08-02 07:24
This is duplicate of #99

**Closed by rallu** 2022-08-02 07:24 UTC
