### ISSUE TITLE
Integration issue | https://eselo-qbj-1618476066-staging-dal.readymage.com/

### ISSUE THREAD

**Issue by maya1941** [klevultd/frontend-sdk#276] opened 2023-06-02 17:30 UTC
There are a couple of issues with our store (https://eselo-qbj-1618476066-staging-dal.readymage.com/)

1) Our deployment hasn't deployed latest "klevu/frontend-sdk" version (v.2.0.6)
2)  Looks like there's a bug in the klevu/frontend-sdk, it sets ID under "sourceObjects" instead of "recentObjects".

<img width="1361" alt="5166186657" src="https://github.com/klevultd/frontend-sdk/assets/135361710/b45c6885-e350-4bb3-a1d1-23704e3d4e52">

Regards,

**Comment by kzulis** [comment] 2023-06-02 20:04
Duplicate of #275

**Comment by jerrypena1** [comment] 2023-06-03 02:43
@maya1941 good catch. I've submitted a pull request with a fix

**Comment by rallu** [comment] 2023-06-05 06:32
Duplicate

**Closed by rallu** 2023-06-05 06:32 UTC
